- hosts: all
  become: yes
  tasks:
    - name: Ensure firewalld is installed
      apt:
        name: firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configure firewalld to allow SSH and HTTP
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - ssh
        - http

    - name: Ensure fail2ban is installed
      apt:
        name: fail2ban
        state: present

    - name: Ensure fail2ban is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: yes
